# Generated by Django 5.2.8 on 2025-11-30 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_base', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota_clinica', models.TextField()),
                ('bloqueado', models.BooleanField(default=False, help_text='Si es True, no se puede editar')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dentista')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='core.fichaclinica')),
            ],
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.paciente'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PREVIO', 'Tratamiento Previo (Existente)'), ('PENDIENTE', 'Pendiente (Por hacer)'), ('REALIZADO', 'Realizado')], default='PENDIENTE', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='core.fichaclinica')),
            ],
        ),
    ]
